# -*- coding: utf-8 -*-
"""re_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w59RIJ0k1Zh-j0Z_EYf9HyKBPNMu2wmO
"""

import re
import pandas as pd

file_path= '/content/drive/MyDrive/Colab Notebooks/data/brunch_data_new.0.csv'
with open(file_path) as f:
    file_list = f.read().splitlines()

delete_in=[]

for i in range (0,len(file_list)):
  eng_sent = re.search('[a-zA-Z]',file_list[i]) 
  qm_sent = re.search('.+“+[가-힣].”.+',file_list[i])
  one_sent = re.search('[ㄱ-ㅎ]|[ㅏ-ㅣ]',file_list[i])
  title_sent = re.search('<>',file_list[i])
  sh_sent = re.search('#',file_list[i])
  if bool(eng_sent) == True:
    delete_in.append(i)
  if bool(qm_sent) == True:
    delete_in.append(i)
  if bool(one_sent) == True:
    delete_in.append(i)
  if bool(title_sent) == True:
    delete_in.append(i)
  if bool(sh_sent) == True:
    delete_in.append(i)

delete_new = sorted(list(set(delete_in)))
delete_lst=list(reversed(delete_new))

for i in range(0,len(delete_new)):
          del file_list[delete_lst[i]]

fin_list = []
for n in range(0,len(file_list)): #len(file_list)
  #print(file_list[n])
  file_list[n]=re.sub('[=|#|-|_|+]','',file_list[n])
  file_list[n]=re.sub('\(\?\)','',file_list[n])
  file_list[n]=re.sub('\(+[가-힣]*.*\)', '', file_list[n])
  file_list[n]=re.sub('"""','',file_list[n])
  file_list[n]=re.sub('^"|"$','',file_list[n])
  file_list[n]=re.sub('^[가-힣](\?|\.)\s','',file_list[n])ㄴ

  fin_list.append(file_list[n])
  #print(file_list[n])

#파일저장
df = pd.DataFrame(fin_list)
#display(df.head(10))
df.to_csv('/content/drive/MyDrive/Colab Notebooks/data/t.csv', index=False, header = False)

